### ISSUE TITLE
Exception consistency

### ISSUE THREAD

**Issue by SuborbitalPigeon** [unitycoders/uc_pircbotx#56]
Some methods throw, and others handle errors. We need to decide where stuff should be handled, then do this.

**Comment by SuborbitalPigeon** [comment]
It boils down to this: handle SQLExceptions in the models, or pass these up to the command code. I think they should be handled at the model level. Any thoughts?

**Comment by SuborbitalPigeon** [comment]
Note to self: all SQL methods should return something. A boolean to indicate failure; or an object when it's a get() style method (returning either a valid object or null to indicate failure).

**Comment by webpigeon** [comment]
I agree it would be best to hide anything sqlite sepsific in the model layer :)
